```{r, results = "asis", echo = FALSE, cache = FALSE}
x <- "\\begin{comment}"
if(opts_knit$get("rmarkdown.pandoc.to") == "latex") {
    if(length(solLabels) != 0) {
        if(!all(is.na(do.call("rbind", solLabels)[, 2]))){
            x <- ""
        }
    }
    if(length(infoLabels) != 0) {
        if(!all(is.na(do.call("rbind", infoLabels)[, 2]))){
            x <- ""
        }
    }
}
cat(x)
```

\newgeometry{margin=0.5in}

# (APPENDIX) Appendix {-}

```{r, results = "asis", echo = FALSE, cache = FALSE}
x <- ""
if(opts_knit$get("rmarkdown.pandoc.to") == "latex"){
    if(length(solLabels) != 0) {
        if(all(is.na(do.call("rbind", solLabels)[, 2]))){
            x <- "\\begin{comment}"
        }
    } else {
        x <- "\\begin{comment}"
    }
}
cat(x)
```

# Answers

```{r, echo = FALSE, results = "asis", cache = FALSE}
if(length(solLabels) > 0) {
    for(i in 1:length(solLabels)) {
        if(!is.na(solLabels[[i]][2][1])) {
            taskCtr <- solLabels[[i]][1]
            refLabel <- solLabels[[i]][2]
            headerName <- solLabels[[i]][3]
            cat(paste0("\\hypertarget{sol", taskCtr, "}{}\n\\bblockS[", headerName, "]{\\phantomsection\\label{tsk", taskCtr, "}", taskCtr, "}\n"))
            cat(refLabel)
            cat(paste0("\n\n\\vspace{\\baselineskip}\\hyperlink{tsk", taskCtr, "}{\\buttonT{Return to task on P\\colpageref{sol", taskCtr, "}}}"))
            cat("\n\\eblockS\n")
        }
    }
}
```

```{r, results = "asis", echo = FALSE, cache = FALSE}
x <- ""
if(opts_knit$get("rmarkdown.pandoc.to") == "latex"){
    if(length(solLabels) != 0) {
        if(all(is.na(do.call("rbind", solLabels)[, 2]))){
            x <- "\\end{comment}"
        }
    } else {
        x <- "\\end{comment}"
    }
}
cat(x)
```

```{r, results = "asis", echo = FALSE, cache = FALSE}
x <- ""
if(opts_knit$get("rmarkdown.pandoc.to") == "latex"){
    if(length(infoLabels) != 0) {
        if(all(is.na(do.call("rbind", infoLabels)[, 2]))){
            x <- "\\begin{comment}"
        }
    } else {
        x <- "\\begin{comment}"
    }
}
cat(x)
```

# Additional information

```{r, echo = FALSE, results = "asis", cache = FALSE}
if(length(infoLabels) > 0) {
    for(i in 1:length(infoLabels)) {
        if(!is.na(infoLabels[[i]][2][1])) {
            infoCtr <- infoLabels[[i]][1]
            refLabel <- infoLabels[[i]][2]
            headerName <- infoLabels[[i]][3]
            cat(paste0("\\hypertarget{info", infoCtr,"}{}\n\\bblockI[", headerName, "]{\\phantomsection\\label{info", infoCtr, "}}\n"))
            cat(refLabel)
            cat(paste0("\n\n\\vspace{\\baselineskip}\\hyperlink{infoRet", infoCtr, "}{\\buttonI{Return to P\\colpageref{infoRet", infoCtr, "}}}"))
            cat("\n\\eblockI\n")
        }
    }
}
```

```{r, results = "asis", echo = FALSE, cache = FALSE}
x <- ""
if(opts_knit$get("rmarkdown.pandoc.to") == "latex"){
    if(length(infoLabels) != 0) {
        if(all(is.na(do.call("rbind", infoLabels)[, 2]))){
            x <- "\\end{comment}"
        }
    } else {
        x <- "\\end{comment}"
    }
}
cat(x)
```

```{r, results = "asis", echo = FALSE, cache = FALSE}
x <- "\\end{comment}"
if(opts_knit$get("rmarkdown.pandoc.to") == "latex") {
    if(length(solLabels) != 0) {
        if(!all(is.na(do.call("rbind", solLabels)[, 2]))){
            x <- ""
        }
    }
    if(length(infoLabels) != 0) {
        if(!all(is.na(do.call("rbind", infoLabels)[, 2]))){
            x <- ""
        }
    }
}
cat(x)
```